pipeline{
    agent any

    environment {
        DOCKERHUB_USERNAME = "wambui843"
        BACKEND_IMAGE = "onboard_forms_backend"
        FRONTEND_IMAGE = "onboard_forms_frontend"
        DOCKER_COMPOSE_FILE = "docker-compose.yml"
    }

    stages {
        stage('Checkout Code'){
            steps{
                git branch: 'main', url: 'https://github.com/Sarah-Wambui/OnBoardForms.git'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                }
            }
        }
        stage('Build Backend Image'){
            steps{
                dir('onBoardForms'){
                    sh "docker build -t $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest ."
                }
            }
        }
        stage('Build Frontend Image'){
            steps{
                dir('onboardui'){
                    sh "docker build -t $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest ."
                }
            }
        }
        stage('Push Images to Docker Hub'){
            steps{
                sh "docker push $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest"
                sh "docker push $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest" 
            }
        }
        stage('Deploy Containers'){
            steps {
                sh '''
                docker pull $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest
                docker pull $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest

                docker stop onboard_forms_backend || true && docker rm onboard_forms_backend || true
                docker stop onboard_forms_frontend || true && docker rm onboard_forms_frontend || true

                docker run -d --name onboard_forms_backend \
                    -e DB_HOST= $DB_HOST \
                    -e DB_USER= $DB_USER \
                    -e DB_PASSWORD= $DB_PASSWORD \
                    -e DB_NAME= $DB_NAME \
                    -p 5000:5000 \
                    $DOCKERHUB_USERNAME/$BACKEND_IMAGE:latest

                docker run -d --name onboard_forms_frontend \
                    -p 3000:3000 $DOCKERHUB_USERNAME/$FRONTEND_IMAGE:latest    
                '''
            }
        }
        stage('Clean Up Local Docker'){
            steps{
                sh 'docker system prune -f'
            }
        }
    } 

    post{
        always{
            echo" Pipeleine finished and workspace cleaned."
            cleanWs()
        }
    }   
}